In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

C:\Users\sergi\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


### data types in numpy
we can have scalars, vectors, matrix, and tensors

scalars is adimensional, is a plain number like `(42)`

vector is unidimensional, is a list of numbers liker `([1, 78, 98, 2, 6])`

matrix is bidimensional, like a table with columns and rows `([[2, 6, 7],[1, 8, 9]])`

    in that case columns is the first dimension, and the observations or rows are the second dimension
    this example has a shape of (2, 3)
   
tensor are multidimensional, with 3 or more dimensions 

In [94]:
a = np.arange(7,20) # arange creates a vector from 0 to n
a.shape
b = np.array([[7, 8, 9],[8, 10, 20]])

we can index the arrays of any dimension
```
a[2]   = 9
b[1,2] = 20
```

if the arrays are not the same length, numpy will apply "broadcasting" to equal the dimensions and shape of the arrays that are being operated

example:

In [36]:
c = np.arange(6, 10); print(c); print(c.shape) # vector 1 dimension, 4 elements
d = np.arange(12,17); print(d) # vectos 1 dimension, 5 elements
c_ = c[:,np.newaxis]; print(c_) # adding 1 dimension, matrix (4,1), 4 elements
table = c[:,np.newaxis] * d 
print(table)

[6 7 8 9]
(4,)
[12 13 14 15 16]
[[6]
 [7]
 [8]
 [9]]
[[ 72  78  84  90  96]
 [ 84  91  98 105 112]
 [ 96 104 112 120 128]
 [108 117 126 135 144]]


### Ndarray Methods

#### Array Conversion

1. `tolist()` The contents of self as a nested list
2. `item(*args)` standard python scalar corresponding to the item at the given location
3. `itemset(*args)` equivalent to but faster than `self[args] = item` (element, value)
4. `tobytes()` returns a Python string showing a copy of the raw contents of data memory.
5. `tofile (file=, sep=”, format=”)` Write the contents of self to the open file object.
6. `astype ({None})` Force conversion of this array to an array with the data type provided as the argument. If the argument is None, or equal to the data type of self, then return a copy of the array.
7. `copy()` returns a copy of the array (which is always single-segment, and ALIGNED)

8. `fill (scalar)` Fill an array with the scalar value (appropriately converted to the type of self). If the scalar value is an array or a sequence, then only the first element is used. This method is usually faster than a[...]=scalar or self.flat=scalar, and always interprets its argument as a scalar.


In [ ]:
a = np.arange(12,21)
a_list = a.tolist(); print(f'a = {a_list}') # converting array to a list

# itemset()
print('\nitemset()') 
print(f'a[2] = {a.item(2)}')  
a.itemset(2, 2); print(a)
print(f'a[2] = {a.item(2)}')

# tobytes() <--- tostring()
print(f'\n\ntobytes()\n{a.tobytes()}')

# tofile()
print('\n\ntofile()')
print('tofile(file= ,sep= ,format= )')
print('tofile(file= "file_name" ,sep= "char to separate items" , format= "%3d format type" )')
a.tofile(file='test.txt', sep=' ', format='%.3s')

# astype()
print('\n\nastype() string')
print(a.astype(np.str_))

# fill(scalar)
#  a.fill(4) 


### Array Shape Manipulation

1. `reshape (newshape, order=’C’)` Return an array that uses the same data as this array but has a new shape given by the newshape tuple (or a scalar to reshape as 1-d). The new shape must define an array with the same total number of elements.
    You should reshape an array when you need to change the number of elements along one of the axes while maintaining the total number of elements. to match the requirements of a particular function or algorithm, or when you want to rearrange the data in an array to make it more amenable to analysis or plotting.

2. 

In [102]:
arr = np.ones((4,5,6))
print(f'SHAPE MANIPULATION \n\narr.shape = {arr.shape}\narr.size  = {arr.size}')

#reshape

SHAPE MANIPULATION 

arr.shape = (4, 5, 6)
arr.size  = 120
